#!/usr/bin/env python3
"""
WAF (Web Application Firewall) Detector
Detects and identifies WAFs and security products
"""

import requests
import json
from datetime import datetime

class WAFDetector:
    """WAF and security product detector"""

    def __init__(self, target_url, output_file=None):
        self.target_url = target_url
        self.output_file = output_file
        self.detected = []
        self.session = requests.Session()
        self.session.headers.update({
            'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36'
        })

        # WAF signatures
        self.waf_signatures = {
            'Cloudflare': {
                'headers': ['cf-ray', 'cf-cache-status', '__cfduid'],
                'cookies': ['__cfduid', '__cflb'],
                'content': ['cloudflare', 'cf-browser-verification']
            },
            'AWS WAF': {
                'headers': ['x-amzn-requestid', 'x-amz-cf-id'],
                'content': ['Access Denied']
            },
            'Akamai': {
                'headers': ['x-akamai-request-id', 'akamai'],
                'content': ['akamai', 'Reference ID']
            },
            'Incapsula': {
                'headers': ['x-iinfo', 'x-cdn'],
                'cookies': ['incap_ses', 'visid_incap'],
                'content': ['_Incapsula_Resource', 'Incapsula incident ID']
            },
            'Sucuri': {
                'headers': ['x-sucuri-id', 'x-sucuri-cache'],
                'content': ['sucuri', 'Access Denied - Sucuri Website Firewall']
            },
            'ModSecurity': {
                'headers': ['mod_security'],
                'content': ['ModSecurity', 'mod_security']
            },
            'Barracuda': {
                'headers': ['barra'],
                'cookies': ['barra_counter_session'],
                'content': ['Barracuda Web Application Firewall']
            },
            'F5 BIG-IP': {
                'cookies': ['BIGipServer', 'F5'],
                'content': ['BIG-IP', 'The requested URL was rejected']
            },
            'Imperva': {
                'headers': ['x-cdn'],
                'cookies': ['incap_ses'],
                'content': ['Imperva', 'Protected by Imperva']
            },
            'Wordfence': {
                'headers': ['wordfence'],
                'content': ['Wordfence', 'Generated by Wordfence']
            },
            'Fortinet FortiWeb': {
                'cookies': ['FORTIWAFSID'],
                'content': ['FortiWeb', 'FORTIGATE']
            },
            'DDoS-Guard': {
                'headers': ['x-ddos-guard'],
                'content': ['ddos-guard']
            },
            'StackPath': {
                'headers': ['x-sp-url'],
                'content': ['stackpath']
            },
            'Radware': {
                'content': ['Radware', 'AppWall']
            },
            'Citrix NetScaler': {
                'cookies': ['ns_af', 'citrix_ns_id', 'NSC_'],
                'content': ['NetScaler']
            },
            'Azure Front Door': {
                'headers': ['x-azure-ref'],
                'content': ['Azure Front Door']
            },
            'AWS CloudFront': {
                'headers': ['x-amz-cf-id', 'x-amz-cf-pop'],
                'content': ['CloudFront']
            }
        }

        # Malicious payloads to trigger WAF
        self.test_payloads = [
            '<script>alert(1)</script>',
            "' OR '1'='1",
            '../../../etc/passwd',
            '../../../../etc/passwd',
            '<?php system($_GET["cmd"]); ?>',
            'UNION SELECT NULL',
        ]

    def scan(self):
        """Run WAF detection scan"""
        print(f"[*] Starting WAF detection on {self.target_url}")

        # Passive detection (normal request)
        self._passive_detection()

        # Active detection (malicious payloads)
        self._active_detection()

        # Save results
        if self.output_file:
            self._save_results()

        return {
            'target': self.target_url,
            'timestamp': datetime.now().isoformat(),
            'detected': self.detected
        }

    def _passive_detection(self):
        """Passive WAF detection via headers and cookies"""
        print("[*] Running passive detection...")

        try:
            response = self.session.get(self.target_url, timeout=10)

            # Check each WAF signature
            for waf_name, signatures in self.waf_signatures.items():
                confidence = 0
                evidence = []

                # Check headers
                if 'headers' in signatures:
                    for header in signatures['headers']:
                        for resp_header in response.headers:
                            if header.lower() in resp_header.lower():
                                confidence += 30
                                evidence.append(f'Header: {resp_header}')

                # Check cookies
                if 'cookies' in signatures:
                    cookies_str = response.headers.get('Set-Cookie', '').lower()
                    for cookie in signatures['cookies']:
                        if cookie.lower() in cookies_str:
                            confidence += 30
                            evidence.append(f'Cookie: {cookie}')

                # Check content
                if 'content' in signatures:
                    for pattern in signatures['content']:
                        if pattern.lower() in response.text.lower():
                            confidence += 20
                            evidence.append(f'Content: {pattern}')

                if confidence > 0:
                    self.detected.append({
                        'waf': waf_name,
                        'confidence': min(confidence, 100),
                        'method': 'passive',
                        'evidence': evidence
                    })
                    print(f"[+] Detected: {waf_name} (confidence: {min(confidence, 100)}%)")

        except Exception as e:
            print(f"[!] Error in passive detection: {e}")

    def _active_detection(self):
        """Active WAF detection using malicious payloads"""
        print("[*] Running active detection...")

        try:
            # Get baseline response
            baseline = self.session.get(self.target_url, timeout=10)
            baseline_status = baseline.status_code

            for payload in self.test_payloads:
                try:
                    # Add payload to URL parameter
                    test_url = f"{self.target_url}{'&' if '?' in self.target_url else '?'}test={payload}"

                    response = self.session.get(test_url, timeout=10)

                    # Check for blocking behavior
                    if response.status_code in [403, 406, 419, 420, 429, 503]:
                        # Check response for WAF signatures
                        for waf_name, signatures in self.waf_signatures.items():
                            if 'content' in signatures:
                                for pattern in signatures['content']:
                                    if pattern.lower() in response.text.lower():
                                        # Check if already detected
                                        if not any(d['waf'] == waf_name for d in self.detected):
                                            self.detected.append({
                                                'waf': waf_name,
                                                'confidence': 90,
                                                'method': 'active',
                                                'evidence': [f'Blocked payload with status {response.status_code}', f'Content: {pattern}']
                                            })
                                            print(f"[+] Detected (active): {waf_name}")
                                        break

                        # Generic WAF detection if no specific signature
                        if response.status_code in [403, 406]:
                            generic_indicators = [
                                'blocked', 'denied', 'forbidden', 'firewall',
                                'security', 'protected', 'access denied',
                                'suspicious', 'malicious', 'threat'
                            ]

                            for indicator in generic_indicators:
                                if indicator in response.text.lower():
                                    if not any(d['waf'] == 'Generic WAF' for d in self.detected):
                                        self.detected.append({
                                            'waf': 'Generic WAF',
                                            'confidence': 70,
                                            'method': 'active',
                                            'evidence': [f'Status {response.status_code}', f'Content: {indicator}']
                                        })
                                        print(f"[+] Detected: Generic WAF/IPS")
                                    break

                except Exception as e:
                    pass

        except Exception as e:
            print(f"[!] Error in active detection: {e}")

    def _save_results(self):
        """Save results to file"""
        results = {
            'target': self.target_url,
            'timestamp': datetime.now().isoformat(),
            'detected': self.detected,
            'summary': {
                'total_detected': len(self.detected),
                'high_confidence': sum(1 for d in self.detected if d['confidence'] >= 80)
            }
        }

        with open(self.output_file, 'w') as f:
            json.dump(results, f, indent=2)


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python3 waf_detector.py <url>")
        print("\nExample:")
        print("  python3 waf_detector.py https://example.com")
        sys.exit(1)

    detector = WAFDetector(sys.argv[1])
    results = detector.scan()

    print(f"\n[+] Detection complete!")

    if results['detected']:
        print(f"    Detected WAF/Security Products:")
        for detection in results['detected']:
            print(f"      - {detection['waf']} (Confidence: {detection['confidence']}%)")
            print(f"        Method: {detection['method']}")
            print(f"        Evidence: {', '.join(detection['evidence'])}")
    else:
        print(f"    No WAF detected")
